package com.co.ijpt.transrisaralda.composites;

import java.text.DateFormat;
import java.util.Date;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.MouseEvents.ClickEvent;
import com.vaadin.event.MouseEvents.ClickListener;
import com.vaadin.server.ThemeResource;
import com.vaadin.server.VaadinRequest;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.VerticalLayout;

public class MainView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,10","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout lytwork;
	@AutoGenerated
	private VerticalLayout lyticonmodules;
	@AutoGenerated
	private Embedded emb3;
	@AutoGenerated
	private Embedded emb2;
	@AutoGenerated
	private Embedded emb1;
	@AutoGenerated
	private AbsoluteLayout lytbanner;
	@AutoGenerated
	private HorizontalLayout lytsysdate;
	@AutoGenerated
	private Label lblsysdate;
	@AutoGenerated
	private HorizontalLayout lytnamebussines;
	@AutoGenerated
	private Label lblnamebussines;
	@AutoGenerated
	private HorizontalLayout lyttoolbar;
	@AutoGenerated
	private Button cmdclosesesion;
	@AutoGenerated
	private MenuBar mbmain;
	/**
	 * 
	 */
	private static final long serialVersionUID = -8042041579781766299L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	
	public MainView(VaadinRequest request) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		DateFormat sd = DateFormat.getDateInstance(DateFormat.LONG);
		String sysdate = sd.format(new Date());
		lblsysdate.setValue(sysdate);
        
        //Establece por defecto sobre la seccion de trabajo el modulo de LOGIN
		lytwork.addComponent(new modLogin(this));
	
		initEvents();
		lyticonmodules.setVisible(false);
	}
	
	public void initEvents(){
		
		emb1.addClickListener(new ClickListener() {		
			@Override
			public void click(ClickEvent event) {
				lytwork.removeAllComponents();
				lytwork.addComponent(new ModAuto());
			}
		});
		
		emb2.addClickListener(new ClickListener() {		
			@Override
			public void click(ClickEvent event) {
				lytwork.removeAllComponents();
				lytwork.addComponent(new ModMant());
			}
		});
		
		emb3.addClickListener(new ClickListener() {		
			@Override
			public void click(ClickEvent event) {
				lytwork.removeAllComponents();
				lytwork.addComponent(new ModAnom());
			}
		});
		
		cmdclosesesion.addClickListener(new Button.ClickListener() {
    		@Override
			public void buttonClick(com.vaadin.ui.Button.ClickEvent event) {
				lytwork.removeAllComponents();
				lytwork.addComponent(new modLogin(null));
			}
		});
	}
	
	
	
	public void successLogin(){
		
		//Por defecto inicia con el modulo de parque automotor cuando INICIA SESION
		lytwork.removeAllComponents();
		lytwork.addComponent(new ModAuto());
		
		// Define a common menu command for all the menu items.
		MenuBar.Command cmdtoauto = new MenuBar.Command() {
		    public void menuSelected(MenuItem selectedItem) {
		    	lytwork.removeAllComponents();
				lytwork.addComponent(new ModAuto());
		    }  
		};
		
		MenuBar.Command cmdtomant = new MenuBar.Command() {
		    public void menuSelected(MenuItem selectedItem) {
				lytwork.removeAllComponents();
				lytwork.addComponent(new ModMant());
		    }  
		};
		
		MenuBar.Command cmdtoanom = new MenuBar.Command() {
		    public void menuSelected(MenuItem selectedItem) {
		    	lytwork.removeAllComponents();
				lytwork.addComponent(new ModAnom());
		    }  
		};
		
		//Inicia menus de barra de herramientas
		MenuItem mimods = mbmain.addItem("Modulos de trabajo", null);
		mimods.addItem("Automotores", null,cmdtoauto);
		mimods.addItem("Mantenimientos", null,cmdtomant);
		mimods.addItem("Anomalias", null, cmdtoanom);
		mbmain.addItem("Nuestra Empresa", null);
		mbmain.addItem("Ayuda", null);		
		
		
		
		lyticonmodules.setVisible(true);
	}

	

    ///////////////////////////////////////////////////////////////////////////////////////
	/////////////////// METODOS AUTOGENERADOS /////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////


	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("1280px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("1280px");
		
		// lyttoolbar
		lyttoolbar = buildLyttoolbar();
		mainLayout.addComponent(lyttoolbar,
				"top:80.0px;right:0.0px;left:0.0px;");
		
		// lytbanner
		lytbanner = buildLytbanner();
		mainLayout.addComponent(lytbanner, "top:0.0px;right:0.0px;left:0.0px;");
		
		// lyticonmodules
		lyticonmodules = buildLyticonmodules();
		mainLayout.addComponent(lyticonmodules, "top:200.0px;left:0.0px;");
		
		// lytwork
		lytwork = new HorizontalLayout();
		lytwork.setImmediate(true);
		lytwork.setWidth("100.0%");
		lytwork.setHeight("1800px");
		lytwork.setMargin(false);
		mainLayout.addComponent(lytwork,
				"top:140.0px;right:-319.0px;left:320.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildLyttoolbar() {
		// common part: create layout
		lyttoolbar = new HorizontalLayout();
		lyttoolbar.setStyleName("black");
		lyttoolbar.setImmediate(false);
		lyttoolbar.setWidth("100.0%");
		lyttoolbar.setHeight("-1px");
		lyttoolbar.setMargin(false);
		
		// mbmain
		mbmain = new MenuBar();
		mbmain.setImmediate(false);
		mbmain.setWidth("-1px");
		mbmain.setHeight("-1px");
		lyttoolbar.addComponent(mbmain);
		lyttoolbar.setComponentAlignment(mbmain, new Alignment(33));
		
		// cmdclosesesion
		cmdclosesesion = new Button();
		cmdclosesesion.setCaption("Salir");
		cmdclosesesion.setImmediate(true);
		cmdclosesesion.setWidth("-1px");
		cmdclosesesion.setHeight("-1px");
		lyttoolbar.addComponent(cmdclosesesion);
		lyttoolbar.setComponentAlignment(cmdclosesesion, new Alignment(34));
		
		return lyttoolbar;
	}

	@AutoGenerated
	private AbsoluteLayout buildLytbanner() {
		// common part: create layout
		lytbanner = new AbsoluteLayout();
		lytbanner.setImmediate(false);
		lytbanner.setWidth("100.0%");
		lytbanner.setHeight("80px");
		
		// lytnamebussines
		lytnamebussines = buildLytnamebussines();
		lytbanner.addComponent(lytnamebussines, "top:0.0px;left:0.0px;");
		
		// lytsysdate
		lytsysdate = buildLytsysdate();
		lytbanner.addComponent(lytsysdate, "top:0.0px;right:0.0px;");
		
		return lytbanner;
	}

	@AutoGenerated
	private HorizontalLayout buildLytnamebussines() {
		// common part: create layout
		lytnamebussines = new HorizontalLayout();
		lytnamebussines.setStyleName("blue");
		lytnamebussines.setImmediate(false);
		lytnamebussines.setWidth("1800px");
		lytnamebussines.setHeight("80px");
		lytnamebussines.setMargin(true);
		
		// lblnamebussines
		lblnamebussines = new Label();
		lblnamebussines.setStyleName("h1");
		lblnamebussines.setImmediate(false);
		lblnamebussines.setWidth("-1px");
		lblnamebussines.setHeight("-1px");
		lblnamebussines
				.setValue("SISTEMA DE INFORMACION - Transportes Risaralda del Norte SA ");
		lytnamebussines.addComponent(lblnamebussines);
		lytnamebussines.setComponentAlignment(lblnamebussines,
				new Alignment(33));
		
		return lytnamebussines;
	}

	@AutoGenerated
	private HorizontalLayout buildLytsysdate() {
		// common part: create layout
		lytsysdate = new HorizontalLayout();
		lytsysdate.setStyleName("blue");
		lytsysdate.setImmediate(false);
		lytsysdate.setWidth("240px");
		lytsysdate.setHeight("80px");
		lytsysdate.setMargin(true);
		
		// lblsysdate
		lblsysdate = new Label();
		lblsysdate.setImmediate(false);
		lblsysdate.setWidth("-1px");
		lblsysdate.setHeight("-1px");
		lblsysdate.setValue("date_system");
		lytsysdate.addComponent(lblsysdate);
		lytsysdate.setComponentAlignment(lblsysdate, new Alignment(6));
		
		return lytsysdate;
	}

	@AutoGenerated
	private VerticalLayout buildLyticonmodules() {
		// common part: create layout
		lyticonmodules = new VerticalLayout();
		lyticonmodules.setStyleName("blue");
		lyticonmodules.setImmediate(false);
		lyticonmodules.setWidth("110px");
		lyticonmodules.setHeight("390px");
		lyticonmodules.setMargin(false);
		
		// emb1
		emb1 = new Embedded();
		emb1.setImmediate(false);
		emb1.setDescription("<strong><i><h2>Automotores</h2></strong></i>");
		emb1.setWidth("70.0%");
		emb1.setHeight("-1px");
		emb1.setSource(new ThemeResource("img/auto.png"));
		emb1.setType(1);
		emb1.setMimeType("image/png");
		lyticonmodules.addComponent(emb1);
		lyticonmodules.setComponentAlignment(emb1, new Alignment(34));
		
		// emb2
		emb2 = new Embedded();
		emb2.setImmediate(false);
		emb2.setDescription("<strong><i><h2>Mantenimientos</h2></strong></i>");
		emb2.setWidth("70.0%");
		emb2.setHeight("-1px");
		emb2.setSource(new ThemeResource("img/mant.png"));
		emb2.setType(1);
		emb2.setMimeType("image/png");
		lyticonmodules.addComponent(emb2);
		lyticonmodules.setComponentAlignment(emb2, new Alignment(34));
		
		// emb3
		emb3 = new Embedded();
		emb3.setImmediate(false);
		emb3.setDescription("<strong><i><h2>Anomalias</h2></strong></i>");
		emb3.setWidth("70.0%");
		emb3.setHeight("-1px");
		emb3.setSource(new ThemeResource("img/anom.png"));
		emb3.setType(1);
		emb3.setMimeType("image/png");
		lyticonmodules.addComponent(emb3);
		lyticonmodules.setComponentAlignment(emb3, new Alignment(34));
		
		return lyticonmodules;
	}

}
