package com.co.ijpt.transrisaralda.composites;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class ModAuto extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,10","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheet_1;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_5;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_4;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_3;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button xxx;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private ComboBox comboBox_2;
	@AutoGenerated
	private ComboBox comboBox_1;
	@AutoGenerated
	private PopupDateField popupDateField_2;
	@AutoGenerated
	private TextField textField_7;
	@AutoGenerated
	private TextField textField_5;
	@AutoGenerated
	private TextField textField_6;
	@AutoGenerated
	private TextField textField_4;
	@AutoGenerated
	private TextField textField_2;
	@AutoGenerated
	private TextField textField_1;
	@AutoGenerated
	private TextField txtplaca;
	@AutoGenerated
	private TextField txtidauto;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ModAuto() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		initAutoForm();
	}
	
	private void initAutoForm(){
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("1024px");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("1024px");
		setHeight("100.0%");
		
		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		mainLayout.addComponent(tabSheet_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setStyleName("minimal");
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("100.0%");
		tabSheet_1.setHeight("100.0%");
		
		// absoluteLayout_3
		absoluteLayout_3 = buildAbsoluteLayout_3();
		tabSheet_1.addTab(absoluteLayout_3, "Nuevo Automotor", null);
		
		// absoluteLayout_4
		absoluteLayout_4 = new AbsoluteLayout();
		absoluteLayout_4.setImmediate(false);
		absoluteLayout_4.setWidth("-1px");
		absoluteLayout_4.setHeight("-1px");
		tabSheet_1.addTab(absoluteLayout_4, "Actualizacion Automotores", null);
		
		// absoluteLayout_5
		absoluteLayout_5 = new AbsoluteLayout();
		absoluteLayout_5.setImmediate(false);
		absoluteLayout_5.setWidth("100.0%");
		absoluteLayout_5.setHeight("100.0%");
		tabSheet_1.addTab(absoluteLayout_5, "Itinerario de Automotores", null);
		
		return tabSheet_1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_3() {
		// common part: create layout
		absoluteLayout_3 = new AbsoluteLayout();
		absoluteLayout_3.setImmediate(false);
		absoluteLayout_3.setWidth("100.0%");
		absoluteLayout_3.setHeight("100.0%");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		absoluteLayout_3.addComponent(verticalLayout_2,
				"top:33.0px;left:30.0px;");
		
		return absoluteLayout_3;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("412px");
		verticalLayout_2.setHeight("580px");
		verticalLayout_2.setMargin(true);
		verticalLayout_2.setSpacing(true);
		
		// txtidauto
		txtidauto = new TextField();
		txtidauto.setCaption("Numero:");
		txtidauto.setImmediate(false);
		txtidauto.setWidth("100.0%");
		txtidauto.setHeight("-1px");
		txtidauto.setRequired(true);
		txtidauto.setInputPrompt("Numero interno asignado en la ampresa");
		txtidauto.setMaxLength(5);
		verticalLayout_2.addComponent(txtidauto);
		
		// txtplaca
		txtplaca = new TextField();
		txtplaca.setCaption("Placa:");
		txtplaca.setImmediate(false);
		txtplaca.setWidth("100.0%");
		txtplaca.setHeight("-1px");
		txtplaca.setTabIndex(1);
		txtplaca.setRequired(true);
		txtplaca.setInputPrompt("ABC 123");
		txtplaca.setMaxLength(10);
		verticalLayout_2.addComponent(txtplaca);
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setCaption("Serial motor:");
		textField_1.setImmediate(false);
		textField_1.setWidth("100.0%");
		textField_1.setHeight("-1px");
		verticalLayout_2.addComponent(textField_1);
		
		// textField_2
		textField_2 = new TextField();
		textField_2.setCaption("Cilindraje:");
		textField_2.setImmediate(false);
		textField_2.setWidth("100.0%");
		textField_2.setHeight("-1px");
		verticalLayout_2.addComponent(textField_2);
		
		// textField_4
		textField_4 = new TextField();
		textField_4.setCaption("Chasis:");
		textField_4.setImmediate(false);
		textField_4.setWidth("100.0%");
		textField_4.setHeight("-1px");
		verticalLayout_2.addComponent(textField_4);
		
		// textField_6
		textField_6 = new TextField();
		textField_6.setCaption("Linea:");
		textField_6.setImmediate(false);
		textField_6.setWidth("100.0%");
		textField_6.setHeight("-1px");
		verticalLayout_2.addComponent(textField_6);
		
		// textField_5
		textField_5 = new TextField();
		textField_5.setCaption("Propietario:");
		textField_5.setImmediate(false);
		textField_5.setWidth("100.0%");
		textField_5.setHeight("-1px");
		verticalLayout_2.addComponent(textField_5);
		
		// textField_7
		textField_7 = new TextField();
		textField_7.setCaption("Capacidad:");
		textField_7.setImmediate(false);
		textField_7.setWidth("100.0%");
		textField_7.setHeight("-1px");
		verticalLayout_2.addComponent(textField_7);
		
		// popupDateField_2
		popupDateField_2 = new PopupDateField();
		popupDateField_2.setCaption("Modelo:");
		popupDateField_2.setImmediate(false);
		popupDateField_2.setWidth("100.0%");
		popupDateField_2.setHeight("-1px");
		verticalLayout_2.addComponent(popupDateField_2);
		
		// comboBox_1
		comboBox_1 = new ComboBox();
		comboBox_1.setCaption("Clase:");
		comboBox_1.setImmediate(false);
		comboBox_1.setWidth("100.0%");
		comboBox_1.setHeight("-1px");
		verticalLayout_2.addComponent(comboBox_1);
		
		// comboBox_2
		comboBox_2 = new ComboBox();
		comboBox_2.setCaption("Marca:");
		comboBox_2.setImmediate(false);
		comboBox_2.setWidth("100.0%");
		comboBox_2.setHeight("-1px");
		verticalLayout_2.addComponent(comboBox_2);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		verticalLayout_2.addComponent(horizontalLayout_1);
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("50px");
		horizontalLayout_1.setMargin(false);
		
		// button_1
		button_1 = new Button();
		button_1.setStyleName("small");
		button_1.setCaption("Reset");
		button_1.setImmediate(true);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		horizontalLayout_1.addComponent(button_1);
		horizontalLayout_1.setComponentAlignment(button_1, new Alignment(33));
		
		// xxx
		xxx = new Button();
		xxx.setCaption("Guardar");
		xxx.setImmediate(true);
		xxx.setWidth("150px");
		xxx.setHeight("-1px");
		horizontalLayout_1.addComponent(xxx);
		horizontalLayout_1.setComponentAlignment(xxx, new Alignment(34));
		
		return horizontalLayout_1;
	}

}
